name: CI/CD Pipeline

# Le workflow est déclenché lors d'un push sur la branche dev
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape pour vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape pour installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Installer les dépendances du projet
      - name: Install dependencies
        run: npm install
 
      - name: Fix Jest Permissions
        run: chmod +x ./node_modules/.bin/jest

      # Exécuter les tests avec Jest
      - name: Run tests
        run: npm test

  deploy:
    # Ce job ne s'exécutera que si le job build a réussi
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Vérifier à nouveau le code du dépôt pour fusionner
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      # Pousser les changements de la branche dev vers master
      - name: Merge dev into master
        run: |
          git config --global user.email "bricardnathan@gmail.com"
          git config --global user.name "Nathan Bricard"
          git checkout master
          git merge origin/dev
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/BeeSoX/TP_CI_CD_NodeJs.git master