name: CI/CD Pipeline

# Le workflow est déclenché lors d'un push sur la branche dev
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape pour vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape pour installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Installer les dépendances du projet
      - name: Install dependencies
        run: npm install

      # Exécuter les tests avec Jest
      - name: Run tests
        run: npm test

  deploy:
    # Ce job ne s'exécutera que si le job build a réussi
    needs: build
    runs-on: ubuntu-latest
    if: success()  # Exécute ce job uniquement si les tests réussissent

    steps:
      # Vérifier à nouveau le code du dépôt pour fusionner
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer Git (nécessaire pour les commandes git)
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Pousser les changements de la branche dev vers master
      - name: Merge dev into master
        run: |
          git checkout master
          git merge origin/dev
          git push origin master