name: Node JS test sum
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@master
      - name: Install of Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Installation des dépendances
        run: npm install
      - name: Exécution des tests
        run: npm test