name: Node JS test sum
on: 
  push:
    branches:
        - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Install of Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Installation des dépendances
        run: npm install
      - name: Fix Jest Permissions
        run: chmod +x ./node_modules/.bin/jest
      - name: Exécution des tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Merge Dev into Master
        run: |
          git checkout master
          git merge origin/dev
          git push origin master